### ISSUE TITLE
Introducción a Laravel

### ISSUE THREAD

**Issue by marcuan** [marcuan/proyectosSistemas2#1]
Lean la guía de instalación: http://laravel.com/docs/5.1/installation

No necesitan instalar el Laravel, lo importante acá es que vean cómo configurar cada una de sus instalaciones para comenzar a trabajar; pueden usar los enlaces del sidebar para seguir estudiando cómo trabaja Laravel.

**Comment by crlsktr** [comment]
No sirve esa onda...

**Comment by crlsktr** [comment]
Lol...
